### ISSUE TITLE
Systematic check of dates & times, ensuring timezone formatting

### ISSUE THREAD

**Issue by JessieLOliver** [QutEcoacoustics/baw-server#279]
Time zones must not be browser dependent, and instead constant to when the recordings were taken, so that people from around the world can evaluate audio data according to when it was recorded
- The challenge is displaying time in a format that is intuitive to users
- Most UI avoid showing times in other timezones at **all** costs.
- There are a few screens where times in multiple timezones may need to be displayed
- More feedback appreciated on this issue in particular from other designers/researchers how they show multiple timezones in a user interface!

Related to https://github.com/QutBioacoustics/baw-client/issues/262

**Comment by Allcharles** [comment]
A few things have changed since this issue was opened, however it is still relevant. All design changes can be dropped as the baw-server UI pages are being replaced by the Angular client (workbench-client) which is being tracked here: https://github.com/QutEcoacoustics/workbench-client/issues/345. To ensure timezone formatting is performed correctly, modifications to the existing models will need to be made.

Baw-server saves timestamps using the ISO-8601 format which does not store the timezone details. We need to append a `timezoneInformation` field to any models which have timestamps. This new field will contain the IANA identifier (among other values) and is similar to how the Site and User models are already setup. Any models which contain timestamps such as the AudioRecording will be updated so that they reference the `timezoneInformation` settings for its parent model (in this case Site).

**Comment by atruskie** [comment]
Checklist of fields to get local time treatement:

- audio_recordings.recorded_date

...and that's it. On reflection all UI timestamps are derived from the recorded_date field so that is the only one that needs to be augmented.
