### ISSUE TITLE
Add better error messages for bad content type headers

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/baw-server#361]
Stack trace:

```
NoMethodError (undefined method `[]=' for nil:NilClass):
  app/controllers/dataset_items_controller.rb:94:in `dataset_item_params'
  app/controllers/dataset_items_controller.rb:53:in `create'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:198:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/action_controller/metal/rendering.rb:10:in `process_action'
```

**Comment by atruskie** [comment]
We narrowed this down to sending a `text/plain` mimetype in the `Content-Type` header when we, in fact, had a JSON payload. User error.

This issue has now been changed to: Add better error messages when bad content type headers are provided.

I'm thinking a solution is to modify the Application Controller to do the validation and to tag controllers with a `json_only` tag so we know when to apply the validation (not all content types are json, but most are)

**Comment by peichins** [comment]
There are some mismatch combinations of content-type header and actual encoding that are possible to detect because they result in no POST parameters. These can be checked and responded to with clear error messages. 

- There are some others that are difficult to detect, which we will not handle (for now). 
- Non-form data (e.g. json) sent with multipart/form-data content-type header will error in the middleware before the rails app when it tries to parse the body as a form. 
- Invalid json sent with an application/json content-type will also cause an error before the rails app
- ultipart/form-data sent with "application/x-www-form-urlencoded" is parsed into a hash with rubbish key and rubbish value. This is not easy to detect in a general way.  It may be necessary to validate that the correct parameters have been sent before referring to them in controller logic, but this is not addressed for this issue.
