### ISSUE TITLE
New tag API route missing notes input

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#464]
Currently the tags controller fails to properly handle a new tag with attached `notes` value.

To replicate:
`POST` `/tags`

Body:

```JSON
{
	"text": "test tag",
	"isTaxanomic": true,
	"typeOfTag": "common_species",
	"notes": {
		"test": 42,
		"value": "testing"
	}
}
```

On request, the following error is given:

![image](https://user-images.githubusercontent.com/3955116/84138052-03442980-aa91-11ea-9c4f-51fdc746592e.png)

**Comment by atruskie** [comment]
You didn't "break" it. The notes parameter just needs to be added to the list of allowed parameters.

This line: https://github.com/QutEcoacoustics/baw-server/blob/master/app/controllers/tags_controller.rb#L72

Actually, it seems like notes is already permitted. Perhaps it is because it's an object instead of a string? 

You can read more about strong params from here: https://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters
