### ISSUE TITLE
Allow include/exclude of custom_fields (Expose site location in filter projection)

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#495]
Expand the site api filter projection list to include `custom_latitude` and `custom_longitude`. The use case for this is to retrieve the locations and names of all sites under a project, and display them on a map with the website client.

**Comment by Allcharles** [comment]
Adding this feature requires some modification to how projection is handled by the server. Currently projection can only occur on SQL fields, with `new_spec_fields` appended to the final result (bug?). Projection needs to be modified such that `custom_fields` are also filterable, and only created if the model has access to the information required to generate them.

**Comment by atruskie** [comment]
This use-case reveals a subtle issue with our current filters:

- the projection include (smartly) uses the include to select a subset of columns from the database
- custom_fields don't exist in the database, so nothing is returned

For the site: we don't allow access to raw lat/lng. So, if we did 
- `include: ["id"]` then the result is not enough information to make the custom field
- `include: ["id", "latitude", "longitude"]` then 
    - if it works, it is a leaky abstraction
    - if it doesn't... well it's correctly raising since we're asking for fields that should not be accessible

I think the correct change here is to attach a scope to custom fields so that they're included in the database query. Then:
- include/exclude would just work
- we could filter on custom fields as well (though this is a potential security violation)

More work needed
