### ISSUE TITLE
Filter recordings by time of day

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#562]
A few users are asking for the ability to filter audio recordings by the time of the day in which they were recorded. Ideally, it would be possible to filter by date by time of day, however an easier solution may be to just add some custom fields to the recordings filter route which achieves this result.

**Comment by atruskie** [comment]
possible solutions:

- add time of day operator to filter
- add custom time of day fields to model

Probably leaning toward the later because:

- sub-operators are not supported in our filter concept
- a cross product of current equality operators with a time of day specific variant seems like a explosion of complexity
- we currently only think time of day would be useful for one model, so best not to over generalize

**Comment by atruskie** [comment]
OK, given the complexities of working with dates in local times, we've gone with an expression syntax which I've proposed here: https://github.com/QutEcoacoustics/baw-server/wiki/API:-Filtering#expressions-experimental
